agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('detail/', AgentDetailView.as_view(), name='agent-detail'),
]

djcrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from leads.views import landing_page, LandingPageView, SignupView
from django.conf import settings

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from leads.models import Agent

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

agents/views.py
from django.shortcuts import reverse
from django.views import generic
#from django.contrib.auth.mixins import LoginRequiredMixin
from .mixin import OrganizerAndLoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
# Create your views here.

class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        #return Agent.objects.all() #if you don't want to filter by organization
        organization = self.request.user.userprofile  #filtering by organization Foreign Key
        return Agent.objects.filter(organization = organization)


class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name  = "agents/agent_create.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self,form):
        agent = form.save(commit=False)
        agent.organization = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(OrganizerAndLoginRequiredMixin , generic.DetailView):
    template_name = "agents/agents_detail.html"

    def get_queryset(self):
        return Agents.objects.all()

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% block content%}  
<a href="{/agents/}">Go back to agents</a>
<hr />
<h1>Create a new agent</h1>
<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit"> Click to submit </button>
</form>
{% endblock content%}  

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content%}       

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class = "w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>

        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create New Agent</a>
        </div>

    </div>
    <div class="flex flex-wrap -m-4">
        {%  for agent in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
            </div>
            <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
                <p class="leading-relaxed text-base">Description here</p>
                <a href="#" class="mt-3 text-blue-500 inline-flex items-center">View this agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
                </a>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
  </div>
</section>
{% endblock content%}  